apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  something.xml: |-
     {{ tpl (.Files.Get "files/something.xml") . | nindent 8 }}

  redis.properties: |-
    redis.cluster.nodes=
    {{- $redis := dict "hosts" (list) -}}
    {{- range $key, $value := .Values.redis.nodes }}
    {{- range $keyP, $valueP := $.Values.redis.ports }}
      {{- $noop := printf "%s:%d" $value (int64 $valueP)  | append $redis.hosts | set $redis "hosts" -}}
    {{- end -}}
    {{- end -}}
    {{- join "," $redis.hosts -}}
